# JDBC in-memory database used by the app and by the H2 console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=SA
spring.datasource.password=

# enable the H2 console and set the path (default is /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# optional: show SQL to help learning
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop